vim.o.expandtab      = true               -- use spaces when <Tab> is inserted
vim.o.tabstop        = 2                  -- number of spaces that <Tab> in file uses
vim.o.softtabstop    = 2                  -- number of spaces that <Tab> uses while editing
vim.o.shiftwidth     = 2                  -- number of spaces to use for (auto)indent step
vim.o.wrap           = false              -- long lines wrap and continue on the next line
vim.o.number         = true               -- print the line number in front of each line
vim.o.background     = "dark"             -- "dark" or "light", used for highlight colors
vim.o.colorcolumn    = "80"               -- columns to highlight
vim.o.signcolumn     = "yes"              -- when and how to display the sign column
vim.o.termguicolors  = true               -- Use more colors
vim.o.timeout        = true               -- time out on mappings and key codes
vim.o.timeoutlen     = 300                -- time out time in milliseconds
vim.o.title          = true               -- let Vim set the title of the window
vim.o.updatetime     = 300                -- after this many milliseconds flush swap file
vim.o.cursorline     = true               -- highlight the screen line of the cursor
vim.o.mouse          = "a"                -- enable the use of mouse clicks
vim.o.scrolloff      = 8                  -- minimum nr. of lines above and below cursor
vim.o.autoindent     = true               -- take indent for new line from previous line
vim.o.backspace      = "indent,eol,start" -- how backspace works at start of line
vim.o.backup         = false              -- keep backup file after overwriting a file
vim.o.confirm        = true               -- ask what to do about unsaved/read-only files
vim.o.showmode       = false              -- message on status line to show current mode
vim.o.showtabline    = 1                  -- tells when the tab pages line is displayed
vim.o.smartcase      = true               -- no ignore case when pattern has uppercase
vim.o.ignorecase     = true               -- ignore case when completing file names
vim.o.smarttab       = true               -- use 'shiftwidth' when inserting <Tab>
vim.o.splitbelow     = true               -- new window from split is below the current one
vim.o.splitright     = true               -- new window is put right of the current one
vim.o.swapfile       = true               -- whether to use a swapfile for a buffer
vim.o.conceallevel   = 3                  -- whether concealable text is shown or hidden
vim.o.list           = true               -- show <Tab> and <EOL>

vim.g.mapleader      = " "
vim.g.maplocalleader = " "
