vim.cmd("highlight clear")

if vim.fn.exists("syntax_on") == 1 then
  vim.cmd("syntax reset")
end

vim.o.background = "dark"
vim.g.colors_name = "vscode-2026"

local c = {
  bg = "#121314",
  surface = "#191A1B",
  float = "#202122",
  raised = "#242526",
  border = "#2A2B2C",
  fg = "#BBBEBF",
  fg_bright = "#C9D1D9",
  muted = "#8C8C8C",
  dim = "#555555",
  blue = "#79C0FF",
  blue_ui = "#3994BC",
  blue_dark = "#276782",
  cyan = "#48A0C7",
  green = "#7EE787",
  orange = "#FFA657",
  purple = "#D2A8FF",
  red = "#FF7B72",
  red_soft = "#F48771",
  yellow = "#E5BA7D",
}

local groups = {
  -- Editor and chrome
  Normal = { fg = c.fg, bg = c.bg },
  NormalNC = { fg = c.fg, bg = c.bg },
  NormalFloat = { fg = c.fg, bg = c.float },
  FloatBorder = { fg = c.border, bg = c.float },
  FloatTitle = { fg = c.fg_bright, bg = c.float, bold = true },
  ColorColumn = { bg = c.raised },
  Cursor = { fg = c.bg, bg = c.fg },
  CursorColumn = { bg = c.raised },
  CursorLine = { bg = c.raised },
  CursorLineNr = { fg = c.fg, bg = c.raised },
  LineNr = { fg = "#858889" },
  SignColumn = { fg = c.muted, bg = c.bg },
  FoldColumn = { fg = c.muted, bg = c.bg },
  Folded = { fg = c.muted, bg = c.surface },
  EndOfBuffer = { fg = c.bg },
  NonText = { fg = c.dim },
  Whitespace = { fg = "#3A3B3C" },
  SpecialKey = { fg = c.dim },
  VertSplit = { fg = c.border, bg = c.bg },
  WinSeparator = { fg = c.border, bg = c.bg },
  WinBar = { fg = c.fg, bg = c.bg },
  WinBarNC = { fg = c.muted, bg = c.bg },
  StatusLine = { fg = c.muted, bg = c.surface },
  StatusLineNC = { fg = c.dim, bg = c.surface },
  TabLine = { fg = c.muted, bg = c.surface },
  TabLineFill = { bg = c.surface },
  TabLineSel = { fg = c.fg, bg = c.bg, bold = true },
  Pmenu = { fg = c.fg, bg = c.float },
  PmenuSel = { fg = "#FFFFFF", bg = "#297AA0" },
  PmenuSbar = { bg = c.raised },
  PmenuThumb = { bg = c.muted },
  PmenuMatch = { fg = c.cyan, bold = true },
  PmenuMatchSel = { fg = "#FFFFFF", bg = "#297AA0", bold = true },
  WildMenu = { fg = "#FFFFFF", bg = "#297AA0" },

  -- Selection and search
  Visual = { bg = c.blue_dark },
  VisualNOS = { bg = "#204F63" },
  Search = { fg = c.fg_bright, bg = "#27566A" },
  IncSearch = { fg = "#FFFFFF", bg = "#297AA0", bold = true },
  CurSearch = { fg = "#FFFFFF", bg = "#297AA0", bold = true },
  Substitute = { fg = "#FFFFFF", bg = "#8B1111" },
  MatchParen = { fg = c.fg_bright, bg = "#31576A", bold = true },

  -- Classic syntax
  Comment = { fg = "#8B949E", italic = true },
  Constant = { fg = c.blue },
  String = { fg = "#A5D6FF" },
  Character = { fg = c.red },
  Number = { fg = c.blue },
  Boolean = { fg = c.blue },
  Float = { fg = c.blue },
  Identifier = { fg = c.orange },
  Function = { fg = c.purple },
  Statement = { fg = c.red },
  Conditional = { fg = c.red },
  Repeat = { fg = c.red },
  Label = { fg = c.blue },
  Operator = { fg = c.red },
  Keyword = { fg = c.red },
  Exception = { fg = c.red },
  PreProc = { fg = c.red },
  Include = { fg = c.red },
  Define = { fg = c.red },
  Macro = { fg = c.blue },
  PreCondit = { fg = c.red },
  Type = { fg = c.blue },
  StorageClass = { fg = c.red },
  Structure = { fg = c.blue },
  Typedef = { fg = c.blue },
  Special = { fg = c.blue },
  SpecialChar = { fg = c.green },
  Tag = { fg = c.green },
  Delimiter = { fg = c.fg_bright },
  SpecialComment = { fg = c.muted, italic = true },
  Debug = { fg = c.purple },
  Underlined = { fg = c.blue, underline = true },
  Ignore = { fg = c.dim },
  Error = { fg = "#FFA198", bg = "#490202" },
  Todo = { fg = c.bg, bg = c.yellow, bold = true },

  -- Diagnostics and messages
  DiagnosticError = { fg = c.red_soft },
  DiagnosticWarn = { fg = c.yellow },
  DiagnosticInfo = { fg = c.blue_ui },
  DiagnosticHint = { fg = c.cyan },
  DiagnosticOk = { fg = c.green },
  DiagnosticUnderlineError = { undercurl = true, sp = c.red_soft },
  DiagnosticUnderlineWarn = { undercurl = true, sp = c.yellow },
  DiagnosticUnderlineInfo = { undercurl = true, sp = c.blue_ui },
  DiagnosticUnderlineHint = { undercurl = true, sp = c.cyan },
  ErrorMsg = { fg = c.red_soft },
  WarningMsg = { fg = c.yellow },
  MoreMsg = { fg = c.green },
  Question = { fg = c.cyan },
  ModeMsg = { fg = c.fg_bright, bold = true },
  Title = { fg = c.blue, bold = true },
  Directory = { fg = c.blue },

  -- Diff and Git
  DiffAdd = { fg = c.green, bg = "#04260F" },
  DiffDelete = { fg = "#FFA198", bg = "#490202" },
  DiffChange = { fg = c.orange, bg = "#3B1E0B" },
  DiffText = { fg = c.orange, bg = "#5A1E02", bold = true },
  Added = { fg = c.green },
  Changed = { fg = c.yellow },
  Removed = { fg = c.red_soft },
  GitSignsAdd = { fg = "#73C991" },
  GitSignsChange = { fg = c.yellow },
  GitSignsDelete = { fg = c.red_soft },
  GitSignsCurrentLineBlame = { fg = c.dim, italic = true },

  -- Treesitter
  ["@comment"] = { link = "Comment" },
  ["@comment.documentation"] = { fg = c.muted, italic = true },
  ["@constant"] = { fg = c.blue },
  ["@constant.builtin"] = { fg = c.blue },
  ["@constant.macro"] = { fg = c.blue },
  ["@string"] = { link = "String" },
  ["@string.escape"] = { fg = c.green, bold = true },
  ["@string.regexp"] = { fg = "#A5D6FF" },
  ["@character"] = { fg = c.red },
  ["@number"] = { fg = c.blue },
  ["@boolean"] = { fg = c.blue },
  ["@function"] = { fg = c.purple },
  ["@function.builtin"] = { fg = c.purple },
  ["@function.call"] = { fg = c.purple },
  ["@function.macro"] = { fg = c.blue },
  ["@method"] = { fg = c.purple },
  ["@method.call"] = { fg = c.purple },
  ["@constructor"] = { fg = c.green },
  ["@parameter"] = { fg = c.fg_bright },
  ["@variable"] = { fg = c.orange },
  ["@variable.builtin"] = { fg = c.blue },
  ["@variable.parameter"] = { fg = c.fg_bright },
  ["@variable.member"] = { fg = c.blue },
  ["@property"] = { fg = c.blue },
  ["@field"] = { fg = c.blue },
  ["@type"] = { fg = c.blue },
  ["@type.builtin"] = { fg = c.blue },
  ["@type.definition"] = { fg = c.blue },
  ["@attribute"] = { fg = c.blue },
  ["@keyword"] = { fg = c.red },
  ["@keyword.function"] = { fg = c.red },
  ["@keyword.operator"] = { fg = c.red },
  ["@keyword.import"] = { fg = c.fg_bright },
  ["@operator"] = { fg = c.red },
  ["@punctuation"] = { fg = c.fg_bright },
  ["@punctuation.bracket"] = { fg = c.fg_bright },
  ["@punctuation.delimiter"] = { fg = c.fg_bright },
  ["@tag"] = { fg = c.green },
  ["@tag.attribute"] = { fg = c.blue },
  ["@tag.delimiter"] = { fg = c.muted },
  ["@markup.heading"] = { fg = c.blue, bold = true },
  ["@markup.link"] = { fg = "#A5D6FF", underline = true },
  ["@markup.link.label"] = { fg = c.blue },
  ["@markup.raw"] = { fg = c.blue },
  ["@markup.quote"] = { fg = c.green },
  ["@markup.list"] = { fg = c.orange },
  ["@markup.strong"] = { bold = true },
  ["@markup.italic"] = { italic = true },

  -- LSP semantic tokens
  ["@lsp.type.class"] = { fg = c.blue },
  ["@lsp.type.decorator"] = { fg = c.blue },
  ["@lsp.type.enum"] = { fg = c.blue },
  ["@lsp.type.enumMember"] = { fg = c.blue },
  ["@lsp.type.function"] = { fg = c.purple },
  ["@lsp.type.interface"] = { fg = c.blue },
  ["@lsp.type.macro"] = { fg = c.blue },
  ["@lsp.type.method"] = { fg = c.purple },
  ["@lsp.type.namespace"] = { fg = c.blue },
  ["@lsp.type.parameter"] = { fg = c.fg_bright },
  ["@lsp.type.property"] = { fg = c.blue },
  ["@lsp.type.struct"] = { fg = c.blue },
  ["@lsp.type.type"] = { fg = c.blue },
  ["@lsp.type.typeParameter"] = { fg = c.blue },
  ["@lsp.type.variable"] = { fg = c.orange },
  ["@lsp.mod.deprecated"] = { strikethrough = true },

  -- Built-in UI and configured plugins
  QuickFixLine = { bg = c.raised },
  qfLineNr = { fg = c.muted },
  LspReferenceText = { bg = "#204553" },
  LspReferenceRead = { bg = "#204553" },
  LspReferenceWrite = { bg = "#27566A" },
  WhichKey = { fg = c.cyan },
  WhichKeyGroup = { fg = c.blue },
  WhichKeyDesc = { fg = c.fg },
  WhichKeySeparator = { fg = c.dim },
  WhichKeyNormal = { fg = c.fg, bg = c.float },
  TroubleNormal = { fg = c.fg, bg = c.surface },
  TroubleNormalNC = { fg = c.muted, bg = c.surface },
  SnacksPickerNormal = { fg = c.fg, bg = c.float },
  SnacksPickerBorder = { fg = c.border, bg = c.float },
  SnacksPickerTitle = { fg = c.fg_bright, bg = c.float, bold = true },
  SnacksPickerMatch = { fg = c.cyan, bold = true },
  SnacksPickerListCursorLine = { fg = "#FFFFFF", bg = "#297AA0" },
  SnacksExplorerNormal = { fg = c.fg, bg = c.surface },
  SnacksNotifierInfo = { fg = c.blue_ui },
  SnacksNotifierWarn = { fg = c.yellow },
  SnacksNotifierError = { fg = c.red_soft },

  -- VS Code-inspired tabs, statusline and breadcrumbs
  BufferLineFill = { bg = c.surface },
  BufferLineBackground = { fg = c.muted, bg = c.surface },
  BufferLineBufferSelected = { fg = c.fg_bright, bg = c.bg },
  BufferLineBufferVisible = { fg = c.fg, bg = c.surface },
  BufferLineSeparator = { fg = c.border, bg = c.surface },
  BufferLineSeparatorSelected = { fg = c.blue_ui, bg = c.bg },
  BufferLineSeparatorVisible = { fg = c.border, bg = c.surface },
  BufferLineIndicatorSelected = { fg = c.blue_ui, bg = c.bg },
  BufferLineModified = { fg = c.blue_ui, bg = c.surface },
  BufferLineModifiedSelected = { fg = c.blue_ui, bg = c.bg },
  BufferLineOffsetSeparator = { fg = c.border, bg = c.surface },
  BufferLineTabSeparator = { fg = c.border, bg = c.surface },
  BufferLineTabSeparatorSelected = { fg = c.blue_ui, bg = c.bg },
  IblIndent = { fg = "#292A2B" },
  IblScope = { fg = "#4A4B4C" },
  NavicText = { fg = c.muted, bg = c.bg },
  NavicSeparator = { fg = c.dim, bg = c.bg },
}

for group, opts in pairs(groups) do
  vim.api.nvim_set_hl(0, group, opts)
end

vim.g.terminal_color_0 = c.bg
vim.g.terminal_color_1 = c.red
vim.g.terminal_color_2 = c.green
vim.g.terminal_color_3 = c.yellow
vim.g.terminal_color_4 = c.blue
vim.g.terminal_color_5 = c.purple
vim.g.terminal_color_6 = c.cyan
vim.g.terminal_color_7 = c.fg
vim.g.terminal_color_8 = c.dim
vim.g.terminal_color_9 = "#FFA198"
vim.g.terminal_color_10 = "#86CF86"
vim.g.terminal_color_11 = "#E0B97F"
vim.g.terminal_color_12 = "#57A3F8"
vim.g.terminal_color_13 = "#AD80D7"
vim.g.terminal_color_14 = "#5BA8CC"
vim.g.terminal_color_15 = "#F0F6FC"
